channels:
  - bioconda
  - conda-forge
  - r
dependencies:
  - snakemake-minimal =5.7.0
  - python =3.6
  - pandas =0.25.0
  - numpy =1.16.4
  - pigz =2.4
  - fastqc =0.11.8
  - multiqc =1.7
  - cutadapt =2.6
  - trimmomatic =0.38
  - gffread =0.11.4
  - bowtie2 =2.3.5
  - samtools =1.9
  - picard =2.18.7
  - r =3.5.1
  - bioconductor-chippeakanno =3.16.0
  - bioconductor-genomicranges =1.34.0
  - bioconductor-iranges =2.16.0
  - r-data.table =1.11.6
  - r-reshape2 =1.4.3
  - r-readxl  =1.3.1
